services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: gereciador_estabelecimento
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: default
    ports:
      - '5432:5432'
